### ISSUE TITLE
혹시 여기 기술 스택들 이미지 어느 곳에서 따오시는 건가요?

### ISSUE THREAD

**Issue by jsw6701** [n0hack/readme-template#1]
이미지 크기가 일정하고 깔끔해서 저도 사용하고 싶어서 찾는데 찾아지지가 않네요

**Comment by nohack-dev** [comment]
@jsw6701 안녕하세요. 휴가 중이었어서 답변이 늦었습니다. icon8이라는 곳에서 무료 아이콘(작은 사이즈)을 사용하고 있습니다.
